name: Python application

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Test usqlite 
      run: |
        rm ports/unix/*.db
        pushd ports/unix
        make clean && make -j USER_C_MODULES=../../examples/usercmodule
        ./micropython < usqlite_test
