name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: | 
        echo "::group::Fetch history and tags"
        git fetch --no-recurse-submodules --shallow-since="2021-07-01" --tags https://github.com/adafruit/circuitpython HEAD
        git fetch --no-recurse-submodules --shallow-since="2021-07-01" origin $GITHUB_SHA
        git repack -d
        echo "::endgroup::"
        CP_VERSION=$(tools/describe)
        echo "$CP_VERSION"
        echo "CP_VERSION=$CP_VERSION" >> $GITHUB_ENV
        echo "cp-version=$CP_VERSION" >> $GITHUB_OUTPUT
        make fetch-all-submodules

    - name: Run check
      run: make -C mpy-cross

    - name: Run distcheck
      run: make fetch-tags
    - name: Run sqlite
      run: make -C ports/unix USER_C_MODULES=examples/usercmodule && ports/unix/micropython < ports/unix/usqlite_test.py
      
