name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      CP_VERSION: "8.2.x"
      MICROPY_CPYTHON3: python3.8
    steps:
#    - name: Set up repository
#      uses: actions/checkout@v3
#      with:
#        submodules: false
#        fetch-depth: 1
#
#    - name: Install dependencies
#      uses: ./.github/actions/deps/submodules
#      with:
#        action: cache
#        version: true
#    - name: Setup External 
#      uses: ./.github/actions/deps/external
#      with:
#        action: cache



    - name: Dump GitHub context
      run: echo "$GITHUB_CONTEXT"
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
    - name: Set up repository
      uses: actions/checkout@v3
      with:
        submodules: false
        fetch-depth: 1
    - name: Set up python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x
    - name: Duplicate USB VID/PID check
      run: python3 -u -m tools.ci_check_duplicate_usb_vid_pid
    - name: Set up submodules
      id: set-up-submodules
      uses: ./.github/actions/deps/submodules
      with:
        version: true
    - name: Set up external
      uses: ./.github/actions/deps/external







    - name: Install toolchain (aarch64)
      if: matrix.mpy-cross == 'static-aarch64'
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-aarch64-linux-gnu
    - name: Install toolchain (mingw)
      if: matrix.mpy-cross == 'static-mingw'
      run: |
        sudo apt-get update
        sudo apt-get install -y mingw-w64

    - name: Build mpy-cross.${{ matrix.mpy-cross }}
      run: make -C mpy-cross -j2 #-f Makefile.${{ matrix.mpy-cross }}

    - name: Set output
      run: |
        echo >> $GITHUB_ENV "EX=${{ env[format('EX_{0}', matrix.mpy-cross)] || matrix.mpy-cross }}"
        echo >> $GITHUB_ENV "OS=${{ env[format('OS_{0}', matrix.mpy-cross)] }}"


  
        #- name: Run distcheck
      #  run: make fetch-tags
    - name: Run sqlite
      run:  |
        make fetch-tags
        make -C mpy-cross
        make -C ports/unix USER_C_MODULES=examples/usercmodule 
        ports/unix/micropython < ports/unix/usqlite_test.py
      
